### ISSUE TITLE
Add the forum's base URL as a custom source

### ISSUE THREAD

**Issue by tobyzerner** [s9e/flarum-ext-mediaembed#1]
I was just thinking – if someone posts a link to another discussion or post in the same forum, it would be cool to expand it into a little box with the discussion title, post author/avatar, and post content.

Haven't thought much about it beyond that, but just thought I'd drop this idea here before I forget.

**Comment by JoshyPHP** [comment]
That wouldn't be a good fit. Mostly what this extension does is turn URLs into iframes or flash objects.

This would be better handled as its own extension.

**Comment by tobyzerner** [comment]
Ah, OK, fair enough :+1:
