### ISSUE TITLE
Support markdown syntax

### ISSUE THREAD

**Issue by lightonflux** [s9e/flarum-ext-mediaembed#2]
Thank you very much for the extension. 

As far as i can see it only supports bbcode-like syntax at the moment. Flarum does not only support bbcode but also Markdown. 

I think it would improve the user experience and make usage more consistent if there was additional syntax that reassembles markdown. 

In the CommonMark discussion the following syntax is often suggested: 

```
  !video[ title ]( url )
  !audio[ title ]( url )
  !youtube[ title ]( url )
```

It is not part of the specification afaik.

So a `!media[]()` would fit the markdown style while being consistent with "codeword" for bbcode.

**Comment by JoshyPHP** [comment]
You don't have to use a BBCode. It will also convert URLs found in plain text. If you just paste a supported YouTube URL anywhere in a post it should be converted into a video.
