### ISSUE TITLE
Help with plugin and latest beta.   (Beta4)

### ISSUE THREAD

**Issue by bwmarrin** [s9e/flarum-ext-mediaembed#4]
I just installed Flarum again from scratch using composer.  I believe that puts me at beta4.  I downloaded and added this plugin to my extensions folder and it shows up under my admin panel.  Then I activated it and posted some youtube links both inside meida tags and outside of them - but they just appear as links.

Am I doing something wrong?  What steps can I take to try and debug this further?

Also! Thanks for all the support to Flarum with extensions! I appreciate your efforts.

**Comment by JoshyPHP** [comment]
I think it's not currently possible to install extensions this way. Starting with beta4 you need to install via Composer. Execute this command in your Flarum directory:

``` sh
composer require s9e/flarum-ext-mediaembed
```

I've just updated the README accordingly.

**Comment by bwmarrin** [comment]
Thanks! So, I deleted the old folder and reinstalled using the above method.  The extension showed up in my admin panel and I enabled it.

Now, if I post the following.  They still just show up as links instead of inline video.  But.. when I edit my post the preview actually shows the embedded videos correctly.  Odd.   Is there something else I can check or try?  I'm happy to help out in anyway possible.

```
https://www.youtube.com/watch?v=lJJ9TcGxhNY
[media]https://www.youtube.com/watch?v=lJJ9TcGxhNY[/media]
```

**Comment by JoshyPHP** [comment]
Try emptying your `storage/cache` directory then disable/reenable the extension. Then create a new thread and post a couple of YouTube URLs.

**Comment by bwmarrin** [comment]
That worked. Thanks @JoshyPHP

**Comment by JoshyPHP** [comment]
Glad it worked. :+1:
