### ISSUE TITLE
wish can support more link with 163music

### ISSUE THREAD

**Issue by DearTanker** [s9e/flarum-ext-mediaembed#6]
look this powerful wordpress plugin : https://github.com/bigfa/nm

**Comment by JoshyPHP** [comment]
Is music.163.com a particularly popular music site? Can you provide a working link to the kind of content that would be embedded? I can't really find any working links on Reddit.

**Comment by JoshyPHP** [comment]
Ok, as it turns out I cannot play any song from this site because they are geographically restricted, which means I can't implement this site or test it, sorry.

**Comment by DearTanker** [comment]
music.163.com is the most popular music service in china.

but it is only work on chinese network.

so i will test it for u.

u can refer to https://github.com/bigfa/nm

**Comment by JoshyPHP** [comment]
I think your best bet is to create a special extension for it. You can use this extension's bootstrap as a base and configure the MediaEmbed plugin using [this documentation](http://s9etextformatter.readthedocs.io/Plugins/MediaEmbed/Add_custom/).
